name: 添加新文案

on:
  issues:
    types: [labeled]

jobs:
  add-copy:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Add copy to JSON file
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          result-encoding: string
          retries: 3
          script: |
            const fs = require('fs');
            const path = require('path');

            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            const username = issue.data.user.login;
            const sentence = issue.data.body.split('### 文案内容')[1].split('### 注意事项')[0].trim();

            const data = JSON.parse(fs.readFileSync(path.resolve('./static/v50.json'), 'utf-8'));
            data.push(sentence);
            fs.writeFileSync(path.resolve('./static/v50.json'), JSON.stringify(data, null, 2));

            await exec('pnpm dev');

            await exec('git config user.email "github-actions[bot]@users.noreply.github.com"');
            await exec('git config user.name "github-actions[bot]"');
            await exec('git add .');
            await exec(`git commit -m "chore: add new copy by @${username}"`);
            await exec('git push');

      - name: Comment on issue and close
        uses: actions/github-script@v7
        with:
          result-encoding: string
          retries: 3
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '✅ 您提交的文案已被添加到仓库中。感谢您的贡献！'
            });

            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            });
